name: Deploy Application to Firebase
on:
  push:
    branches:
      - master
jobs:
  build-deploy-firebase:
    name: Build And Deploy Web Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name : Inject Version
        run: |
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID" >> .env
          echo "GITHUB_SHA=$GITHUB_SHA" >> .env
      - name: Build
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

